---
version: 0.2

phases:
  install:
    commands:
      - echo "Install NGINX"
      - sudo yum update -y
      - sudo yum install nginx -y
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the code"
      - cp index.html /usr/share/nginx/html/index.html
  post_build:
    commands:
      - echo "Starting NGINX without systemctl"
      - sudo nginx -c /etc/nginx/nginx.conf  # Start NGINX manually
      - sudo nginx -t  # Test the NGINX configuration
      - sudo ps aux | grep nginx  # Confirm NGINX is running

artifacts:
  files:
    - index.html
  discard-paths: yes
